name: Cart CI Pipeline
on:
  push:
    branches:
      - '*'
      - '!master'
run-name: ${{ github.sha }} | ${{ github.event.head_commit.message }}
jobs:
  call-workflow-passing-data:
    uses: tech-spaces/github-reusable-actions/.github/workflows/ci-dev-branch.yml@main