name: Cart CI Pipeline
on:
  push:
    branches:
      - '*'
      - '!master'
run-name: ${{ github.sha }} | ${{ github.event.head_commit.message }}
jobs:
  build:
    runs-on: self-hosted
    steps:
      - users: actions/checkout@v4
      - run: |
          echo

