name: Main Branch Pipeline
on:
  push:
    branches:
      - 'main'
run-name: ${{ github.sha }} | ${{ github.event.head_commit.message }}
jobs:
  jobs:
    call-workflow:
     uses: tech-spaces/github-reusable-actions/.github/workflows/ci-main.yml@main