name: Cart CI Pipeline
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - users: actions/checkout@v4
      - run: |
          echo

  tests:
   runs-on: self-hosted
   needs: build
   steps:
      - uses: actions/checkout@v4
      - run: |
          echo

Dev:
  runs-on: self-hosted
  needs: tests
  environment: DEV
  steps:
    - uses: actions/checkout@v4
    - run: |
        echo
  
QA:
    runs-on: self-hosted
    needs: DEV
    environment: QA
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo

UAT:
  runs-on: self-hosted
  needs: QA
  environment: UAT
  steps:
      - uses: actions/checkout@v4
      - run: |
          echo


PRO:
  runs-on: self-hosted
  needs: UAT
  environment: PROD
  steps:
      - uses: actions/checkout@v4
      - run: |
          echo
